# Generated by Django 5.1.7 on 2025-08-27 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_alter_order_customer_remove_order_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_checkout_id', models.CharField(max_length=100, unique=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid'), ('FAILED', 'failed'), ('CANCELED', 'canceled')], default='PENDING', max_length=20)),
                ('has_paid', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='store.order')),
            ],
            options={
                'indexes': [models.Index(fields=['stripe_checkout_id'], name='cart_paymen_stripe__505e57_idx'), models.Index(fields=['stripe_payment_intent_id'], name='cart_paymen_stripe__cbf949_idx')],
            },
        ),
    ]
